# Generated by Django 6.0.2 on 2026-03-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivero', '0003_registroaccion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
