# Generated by Django 6.0.2 on 2026-03-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivero', '0004_delete_curso_fichatecnica_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnica',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
